---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: syslog-ci
- name: release-repo
- name: release-version

outputs:
  - name: final-release-repo

run:
  path: syslog-ci/.concourse/tasks/create-final-release/task

params:
  PRIVATE_YML:
